version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/strava-explorer"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/aqi-map"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/isochrones"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/gateway"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
